SW_ROOT_DIR=../..
EWOKOS_ROOT_DIR = $(SW_ROOT_DIR)/..
SYS_ROOT_DIR = $(EWOKOS_ROOT_DIR)/system
include $(SW_ROOT_DIR)/make.inc

BUILD_DIR = $(SYS_ROOT_DIR)/build/$(HW)

CFLAGS += -I. -Iinclude -Iinclude/imgui -I $(BUILD_DIR)/include -I../external
CXXFLAGS += -I. -Iinclude -Iinclude/imgui -I $(BUILD_DIR)/include -I../external

# ImGui C++ source files
LIB_IMGUI_OBJS = \
	imgui.o \
	imgui_draw.o \
	imgui_tables.o \
	imgui_widgets.o \
	backends/imgui_impl_pgl_geometry.o \
	backends/imgui_impl_portablegl.o

IMGUI = $(BUILD_DIR)/lib/libimgui.a

$(IMGUI): $(LIB_IMGUI_OBJS)
	$(AR) rcs $(IMGUI) $(LIB_IMGUI_OBJS)
	mkdir -p $(BUILD_DIR)/include/imgui
	cp -r *.h $(BUILD_DIR)/include/imgui/
	mkdir -p $(BUILD_DIR)/include/imgui/backends
	cp -r backends/*.h $(BUILD_DIR)/include/imgui/backends/
	mkdir -p $(BUILD_DIR)/include/imgui/misc/cpp
	cp -r misc/cpp/*.h $(BUILD_DIR)/include/imgui/misc/cpp/
	mkdir -p $(BUILD_DIR)/include/imgui/misc/freetype
	cp -r misc/freetype/*.h $(BUILD_DIR)/include/imgui/misc/freetype/

# Compile C++ files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Compile backend C++ files
backends/%.o: backends/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(LIB_IMGUI_OBJS)
	rm -f $(IMGUI)
