all: basic_libs
	@echo "all done."

basic_libs:
	cd SDL2;make
	cd portablegl;make
	cd ffmpeg;make
	cd litehtml;make
	cd Widget++;make

clean:
	cd SDL2;make clean
	cd portablegl;make clean
	cd ffmpeg;make clean
	cd litehtml;make clean
	cd Widget++;make clean
