
all: 
	cd 3ddemo;make
	cd tetris; make
	cd Fireworks; make
	cd anim; make
	cd kimi_chat; make
	cd xDraw; make

clean: 
	cd 3ddemo;make clean
	cd tetris; make clean
	cd Fireworks; make clean
	cd anim; make clean
	cd kimi_chat; make clean
	cd xDraw; make clean
