
all:
	cd 3ddemo;make
	cd doom; make
	cd doomgl; make
	cd Fireworks; make
	cd VideoPlayer; make
	cd calculator; make
	cd calendar; make
	cd gears; make
	cd imgui_demo; make
	cd matrix; make
	cd waterdrops; make
	cd xBrowser; make

clean:
	cd 3ddemo;make clean
	cd doom; make clean
	cd doomgl; make clean
	cd Fireworks; make clean
	cd VideoPlayer; make clean
	cd calculator; make clean
	cd calendar; make clean
	cd gears; make clean
	cd imgui_demo; make clean
	cd matrix; make clean
	cd waterdrops; make clean
	cd xBrowser; make clean
