
all:
	cd 3ddemo;make
	cd Fireworks; make
	cd calculator; make
	cd calendar; make
	cd gears; make
	cd imgui_demo; make
	cd matrix; make
	cd waterdrops; make

clean:
	cd 3ddemo;make clean
	cd Fireworks; make clean
	cd calculator; make clean
	cd calendar; make clean
	cd gears; make clean
	cd imgui_demo; make clean
	cd matrix; make clean
	cd waterdrops; make clean
